"""add_schedule_id_to_event_seat_grades

Revision ID: 06df2c7f803d
Revises: f274031cba85
Create Date: 2025-12-28 23:15:40.140299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06df2c7f803d'
down_revision: Union[str, Sequence[str], None] = 'f274031cba85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # schedule_id 컬럼 추가 (nullable=True로 설정하여 기존 데이터와 호환)
    op.add_column('event_seat_grades', sa.Column('schedule_id', sa.Integer(), nullable=True))
    # ForeignKey 제약 조건 추가
    op.create_foreign_key(
        'fk_event_seat_grades_schedule_id',
        'event_seat_grades',
        'event_schedules',
        ['schedule_id'],
        ['id']
    )
    # 인덱스 추가 (성능 향상)
    op.create_index(
        op.f('ix_event_seat_grades_schedule_id'),
        'event_seat_grades',
        ['schedule_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_seat_grades_schedule_id'), table_name='event_seat_grades')
    op.drop_constraint('fk_event_seat_grades_schedule_id', 'event_seat_grades', type_='foreignkey')
    op.drop_column('event_seat_grades', 'schedule_id')
    # ### end Alembic commands ###
