"""add_sub_genre_and_is_hot_to_events

Revision ID: 597af238862c
Revises: db884318d4dc
Create Date: 2025-12-27 01:51:15.096580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597af238862c'
down_revision: Union[str, Sequence[str], None] = 'db884318d4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ENUM 타입 생성
    eventsubgenre_enum = sa.Enum('BALLAD', 'ROCK_METAL', 'RAP_HIPHOP', 'JAZZ_SOUL', 'DINNER_SHOW', 'FOLK_TROT', 'INTERNATIONAL', 'FESTIVAL', 'FAN_CLUB', 'INDIE', 'TALK_LECTURE', name='eventsubgenre')
    eventsubgenre_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('events', sa.Column('sub_genre', eventsubgenre_enum, nullable=True))
    op.add_column('events', sa.Column('is_hot', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_hot')
    op.drop_column('events', 'sub_genre')
    # ENUM 타입 삭제
    sa.Enum(name='eventsubgenre').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
