"""add_event_fields_and_related_tables

Revision ID: 8f070a0898d0
Revises: 04396c0a19c0
Create Date: 2025-12-27 00:59:04.934111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f070a0898d0'
down_revision: Union[str, Sequence[str], None] = '04396c0a19c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    eventgenre_enum = postgresql.ENUM('MUSICAL', 'THEATER', 'CONCERT', 'EXHIBITION', 'SPORTS', 'ETC', name='eventgenre')
    eventgenre_enum.create(op.get_bind(), checkfirst=True)
    
    ticketreceiptmethod_enum = postgresql.ENUM('DELIVERY', 'ON_SITE', 'BOTH', name='ticketreceiptmethod')
    ticketreceiptmethod_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('event_description_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_description_images_id'), 'event_description_images', ['id'], unique=False)
    op.create_table('event_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('running_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_schedules_id'), 'event_schedules', ['id'], unique=False)
    # ticketgrade enum 타입은 이미 존재하므로 재사용
    ticketgrade_enum = postgresql.ENUM('VIP', 'R', 'S', 'A', name='ticketgrade', create_type=False)
    
    op.create_table('event_seat_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.String(), nullable=False),
    sa.Column('grade', ticketgrade_enum, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_seat_grades_id'), 'event_seat_grades', ['id'], unique=False)
    op.add_column('events', sa.Column('genre', eventgenre_enum, nullable=True))
    op.add_column('events', sa.Column('ticket_receipt_method', ticketreceiptmethod_enum, nullable=True))
    op.add_column('events', sa.Column('sales_open_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('events', 'event_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('events', 'sales_open_date')
    op.drop_column('events', 'ticket_receipt_method')
    op.drop_column('events', 'genre')
    # Drop enum types
    op.execute('DROP TYPE IF EXISTS ticketreceiptmethod')
    op.execute('DROP TYPE IF EXISTS eventgenre')
    op.drop_index(op.f('ix_event_seat_grades_id'), table_name='event_seat_grades')
    op.drop_table('event_seat_grades')
    op.drop_index(op.f('ix_event_schedules_id'), table_name='event_schedules')
    op.drop_table('event_schedules')
    op.drop_index(op.f('ix_event_description_images_id'), table_name='event_description_images')
    op.drop_table('event_description_images')
    # ### end Alembic commands ###
