"""add_schedule_id_to_tickets_and_bookings

Revision ID: edb2071fb96b
Revises: 06df2c7f803d
Create Date: 2025-12-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb2071fb96b'
down_revision: Union[str, Sequence[str], None] = '06df2c7f803d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # tickets 테이블에 schedule_id 컬럼 추가
    op.add_column('tickets', sa.Column('schedule_id', sa.Integer(), nullable=True))
    # ForeignKey 제약 조건 추가
    op.create_foreign_key(
        'fk_tickets_schedule_id',
        'tickets',
        'event_schedules',
        ['schedule_id'],
        ['id']
    )
    # 인덱스 추가
    op.create_index(
        op.f('ix_tickets_schedule_id'),
        'tickets',
        ['schedule_id'],
        unique=False
    )
    
    # bookings 테이블에 schedule_id 컬럼 추가
    op.add_column('bookings', sa.Column('schedule_id', sa.Integer(), nullable=True))
    # ForeignKey 제약 조건 추가
    op.create_foreign_key(
        'fk_bookings_schedule_id',
        'bookings',
        'event_schedules',
        ['schedule_id'],
        ['id']
    )
    # 인덱스 추가
    op.create_index(
        op.f('ix_bookings_schedule_id'),
        'bookings',
        ['schedule_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # bookings 테이블에서 schedule_id 제거
    op.drop_index(op.f('ix_bookings_schedule_id'), table_name='bookings')
    op.drop_constraint('fk_bookings_schedule_id', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'schedule_id')
    
    # tickets 테이블에서 schedule_id 제거
    op.drop_index(op.f('ix_tickets_schedule_id'), table_name='tickets')
    op.drop_constraint('fk_tickets_schedule_id', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'schedule_id')
    # ### end Alembic commands ###

