"""add_user_contact_and_address_fields

Revision ID: f274031cba85
Revises: 597af238862c
Create Date: 2025-12-28 22:17:23.554987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f274031cba85'
down_revision: Union[str, Sequence[str], None] = '597af238862c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone3', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('detail_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'detail_address')
    op.drop_column('users', 'address')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'phone3')
    op.drop_column('users', 'phone2')
    op.drop_column('users', 'phone1')
    # ### end Alembic commands ###
